apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flood-detection-backend.fullname" . }}
  labels:
    {{- include "flood-detection-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "flood-detection-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flood-detection-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flood-detection-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MINIO_ENDPOINT
              value: {{ .Values.env.MINIO_ENDPOINT | quote }}
            - name: PYTHONPATH
              value: {{ .Values.env.PYTHONPATH | quote }}
            - name: MODEL_CONFIG_FILE
              value: {{ .Values.model.configFile | quote }}
            - name: MODEL_CHECKPOINT_FILE
              value: {{ .Values.model.checkpointFile | quote }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "flood-detection-backend.fullname" . }}-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "flood-detection-backend.fullname" . }}-secrets
                  key: minio-secret-key
            - name: SH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "flood-detection-backend.fullname" . }}-secrets
                  key: sh-client-id
            - name: SH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "flood-detection-backend.fullname" . }}-secrets
                  key: sh-client-secret
            - name: GRADIO_MCP_SERVER
              value: "true"
            - name: MPLCONFIGDIR
              value: "/tmp/matplotlib"
            - name: HOME
              value: "/tmp"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: models-storage
              mountPath: /app/models
            - name: configs-storage
              mountPath: /app/configs
      volumes:
        - name: models-storage
          {{- if .Values.persistence.models.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "flood-detection-backend.fullname" . }}-models
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: configs-storage
          {{- if .Values.persistence.configs.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "flood-detection-backend.fullname" . }}-configs
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
